### ISSUE TITLE
Pagination and sorting issue

### ISSUE THREAD

**Issue by thebeatlesteam2** [krishna2614/The-Beatles#15]
when we click on next page button, we are not taken to the page which should be opened. This can be caused by the errors in code for pagination and sorting features.

**Comment by YamunaDorsala** [comment]
<img width="960" alt="Screenshot 2023-10-26 193207" src="https://github.com/krishna2614/The-Beatles/assets/149100654/3863a833-196b-44a5-ab4e-00c11ebacb47">

Here, we have pagination with the sorting which is not working because sorting is not working from the second page. The issue here was the url because for sorting, we were using “sortby” and “sort” keywords and for the pagination “page” keyword. So, when we use pagination or go to the other page then “sortby” and “sort” keywords get overwritten and sorting does not work.
Issue is fixed
